"""drop the restaurantpizza table and replace it with the new one

Revision ID: b6d482f8b768
Revises: 8463477cf54f
Create Date: 2025-06-17 15:29:39.540723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d482f8b768'
down_revision = '8463477cf54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('restaurant_pizza')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_pizza',
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], name='restaurant_pizza_pizza_id_fkey'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='restaurant_pizza_restaurant_id_fkey'),
    sa.PrimaryKeyConstraint('restaurant_id', 'pizza_id', name='restaurant_pizza_pkey')
    )
    op.drop_table('restaurant_pizzas')
    # ### end Alembic commands ###
